[build]
  command = "pip install -r requirements.txt && python -m pip install --upgrade pip"
  publish = "static"
  functions = "functions"

[build.environment]
  PYTHON_VERSION = "3.9"
  FLASK_APP = "web_app.py"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
